### ISSUE TITLE
logs: incorrect `service.name` transformation

### ISSUE THREAD

**Issue by sudomateo** [DataDog/opentelemetry-mapping-go#356]
When the `service.name` attribute is set as a resource attribute or as an attribute on the log, the Datadog user interface shows a JSON object instead of the name of the service.

This issue actually spawns a larger discussion about how the `transform` function is meant to work. Specifically, the `transform` function retrieves the value for `service`, among others, from either resource attributes or attributes on the log. It then uses that `service` value to set the `Service` field on the [`datadogV2.HTTPLogItem`](https://github.com/DataDog/datadog-api-client-go/blob/e7f356b93d37e1d9ea3f5b381ec6d6e650cd3692/api/datadogV2/model_http_log_item.go#L13-L34). Since values can be set from both resource attributes or attributes on the log, it's not clear which method operators should be using in their code. Perhaps this should be broken out into a separate issue for further discussion. Either way, I'm bringing it up here because it was a bit confusing when reading the code.

https://github.com/DataDog/opentelemetry-mapping-go/blob/6e80d7ed923d9daa6a1245c7bc4afff2983fbbe1/pkg/otlp/logs/transform.go#L78-L80

Here's the `transform` processor I used to set the `service.name` attribute on the log.

```yaml
processors:
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["service.name"], "sudomateo")
          - set(attributes["ddtags"], "source:sudomateo")
```

Notice how this appears incorrectly as a JSON object in the Datadog user interface. With this incorrect behavior I cannot use `service:sudomateo` to filter logs.

<img width="1040" alt="Screenshot 2024-07-02 at 19 12 57" src="https://github.com/DataDog/opentelemetry-mapping-go/assets/24284972/c3a07fd8-4a61-4d11-923a-639a4684c293">

<img width="739" alt="Screenshot 2024-07-02 at 19 12 03" src="https://github.com/DataDog/opentelemetry-mapping-go/assets/24284972/2c8201e7-e602-47ca-86db-86f140e4e874">

**Comment by liustanley** [comment]
This should be fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34420.

**Comment by liustanley** [comment]
> > This should be fixed in [open-telemetry/opentelemetry-collector-contrib#34420](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34420).
> 
> Thank you. I'll give it a test when the beta is live then.

Sounds good, you can either wait until the beta is live or you can enable the `exporter.datadogexporter.UseLogsAgentExporter` feature flag to fix this issue.

**Comment by jackgopack4** [comment]
Hi @sudomateo have you been able to test the fix? Are you still experiencing this issue?

**Comment by sudomateo** [comment]
> Hi [@sudomateo](https://github.com/sudomateo) have you been able to test the fix? Are you still experiencing this issue?

Hey! Must have missed this when I got back from vacation. I just tested with `otelcol-contrib` version `v0.111.0` which has the `exporter.datadogexporter.UseLogsAgentExporter` feature gate enabled be default. Looks good!

```
> otelcol-contrib --version
otelcol-contrib version 0.111.0
```

```yaml
---
receivers:
  filelog:
    include:
    - /tmp/foo.log

processors:
  batch:
  transform:
    log_statements:
    - context: log
      statements:
      - set(attributes["service.name"], "sudomateo")
      - set(attributes["ddtags"], "source:sudomateo")

exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
      site: us5.datadoghq.com

extensions:
  health_check:
  pprof:

service:
  extensions: [health_check, pprof]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [transform, batch]
      exporters: [datadog]
```

![Image](https://github.com/user-attachments/assets/8807ab5b-477d-4dc7-8ab1-fc06421b0e0f)
