### ISSUE TITLE
Update log transformer to set logger.name

### ISSUE THREAD

**Issue by IGx89** [DataDog/opentelemetry-mapping-go#411]
Hello! I've been doing A/B comparisons between sending logs from my .NET app to Datadog using the Datadog SDK and the OpenTelemetry SDK. Once difference is that logs from the Datadog SDK (technically console out JSON parsing by the Datadog agent) have a "Logger Name" box under Event Attributes indicating the name of the logger (full class name with namespace) while that is missing when using the OpenTelemetry SDK.

After reading through docs and source code, I believe that data is missing due to the log transformer here ignoring that data. In https://github.com/DataDog/opentelemetry-mapping-go/blob/pkg/otlp/logs/v0.21.0/pkg/otlp/logs/translator.go#L73 it gets ScopeLogs which contains the logger name (`ScopeLogs.Scope().Name()`) but the code never calls that method. It should ideally call that method and then store it in AdditionalProperties["logger.name"] on the HTTPLogItem object (best I can tell).

Could that data be passed through so we're able to query our logs by logger name when using the OpenTelemetry SDK?

**Comment by oldium** [comment]
We are using the following workaround on the OpenTelemetry Collector side:

```
      transform:
        log_statements:
          - statements:
              - set(log.attributes["logger.name"], instrumentation_scope.name) where instrumentation_scope.version == "" and instrumentation_scope.name != ""
              - set(log.attributes["logger.thread_name"], log.attributes["thread.name"]) where log.attributes["thread.name"] != nil
```
